server:
  port: 8082

# id сервера-приложения eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: books
        uri: http://localhost:8083
        predicates:
          - Path=/books-client/**
        filters:
          - RewritePath=/books-client/(?<remaining>.*),/$\{remaining}
      routes[1]:
        id: readers
        uri: http://localhost:8084
        predicates:
          - Path=/readers-client/**
        filters:
          - RewritePath=/readers-client/(?<remaining>.*),/$\{remaining}
      routes[2]:
        id: issues
        uri: http://localhost:8085
        predicates:
          - Path=/issues-client/**
        filters:
          - RewritePath=/issues-client/(?<remaining>.*),/$\{remaining}


# url, где будет происходить регистрация микросервисов и другие важные действия
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka